# Generated by Django 5.0.2 on 2024-02-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrp_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='Unassigned', max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('unknown', 'UNKNOWN'), ('registered', 'REGISTERED'), ('unregistered', 'UNREGISTERED')], default='UNKNOWN', max_length=32),
        ),
    ]
