# Generated by Django 5.0.2 on 2024-02-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrp_registry', '0002_device_name_device_status_alter_device_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(default='Unknown', max_length=32),
        ),
    ]
